name: 'beanstalk-envs-action'
description:
  'Create a envvars.config file for AWS Elastic Beanstalk deployments'
author: 'luke@basal.dev'

branding:
  icon: 'file-plus'
  color: 'gray-dark'

inputs:
  directory:
    description: 'The directory to put the envfile in (default: .ebextensions)'
    required: false
    default: '.ebextensions'
  filename:
    description: 'Name of the config file (default: envvars.config)'
    required: false
    default: 'envvars.config'
  json:
    description:
      'JSON representation of environment variable key/values to set as direct
      values'
    required: false
  aws_secret_references:
    description:
      'JSON string containing AWS Secrets Manager partial references (format:
      "secretName:secretKey")'
    required: false
  aws_region:
    description:
      'AWS region for Secrets Manager ARNs (required when using
      aws_secret_references)'
    required: true
  aws_access_key_id:
    description:
      'AWS access key ID (must be provided with aws_secret_access_key and
      aws_session_token, or leave all three empty to use scope credentials)'
    required: false
  aws_secret_access_key:
    description:
      'AWS secret access key (must be provided with aws_access_key_id and
      aws_session_token, or leave all three empty to use scope credentials)'
    required: false
  aws_session_token:
    description:
      'AWS session token (must be provided with aws_access_key_id and
      aws_secret_access_key, or leave all three empty to use scope credentials)'
    required: false
  sort_keys:
    description: 'Sort environment variables alphabetically by key'
    required: false
    default: 'false'
  fail_on_empty:
    description: 'Fail if any environment variable has an empty value'
    required: false
    default: 'false'
  rendered_file_path:
    description:
      'Path to generate test config file with resolved secret values (only when
      aws_secret_references input is provided)'
    required: false

outputs:
  result:
    description: 'envvars.config file'
  test_config:
    description:
      'envvars-test.config file (only when rendered_file_path is provided)'

runs:
  using: 'node20'
  main: 'dist/index.js'
